version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 7101:4200
    volumes:
      - ./src:/app/src
    command: npm run start:dev
    user: root
    env_file: 
      - .env
    networks:
      - docker-network
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - docker-network
    user: root
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - "./data:/bitnami/postgresql"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    env_file: 
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - docker-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge